import './../globals.css'
import type { Metadata } from 'next'
import { JetBrains_Mono } from 'next/font/google'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const font = JetBrains_Mono({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Kết Kết's Blog",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <main>
          <div className='pb-48'><Header/></div>
            {children}
          <Footer/>
        </main>
      </body>
    </html>
  )
}
